#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Marcus Quinn
# shellcheck disable=SC2001,SC2034,SC2181,SC2317
set -euo pipefail

# Version Manager for AI DevOps Framework
# Manages semantic versioning and automated version bumping
#
# Author: AI DevOps Framework
# Version: 1.1.0

# Source shared constants (provides sed_inplace, print_*, color constants)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/shared-constants.sh"

# Repository root directory
# First try git (works when called from any location within a repo)
# Fall back to script-relative path (for when script is sourced or tested standalone)
if git rev-parse --show-toplevel &>/dev/null; then
	REPO_ROOT="$(git rev-parse --show-toplevel)"
else
	REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fi
VERSION_FILE="$REPO_ROOT/VERSION"

# Function to get current version
get_current_version() {
	if [[ -f "$VERSION_FILE" ]]; then
		cat "$VERSION_FILE"
	else
		echo "1.0.0"
	fi
	return 0
}

# Function to bump version
bump_version() {
	local bump_type="$1"
	local current_version
	current_version=$(get_current_version)

	local major minor patch
	IFS='.' read -r major minor patch <<<"$current_version"

	case "$bump_type" in
	"major")
		major=$((major + 1))
		minor=0
		patch=0
		;;
	"minor")
		minor=$((minor + 1))
		patch=0
		;;
	"patch")
		patch=$((patch + 1))
		;;
	*)
		print_error "Invalid bump type. Use: major, minor, or patch"
		return 1
		;;
	esac

	local new_version="$major.$minor.$patch"
	echo "$new_version" >"$VERSION_FILE"
	echo "$new_version"
	return 0
}

# Function to check changelog has entry for version
check_changelog_version() {
	local version="$1"
	local changelog_file="$REPO_ROOT/CHANGELOG.md"

	if [[ ! -f "$changelog_file" ]]; then
		print_warning "CHANGELOG.md not found"
		return 1
	fi

	# Check if version entry exists
	if grep -q "^\## \[$version\]" "$changelog_file"; then
		print_success "CHANGELOG.md: $version ✓"
		return 0
	else
		print_error "CHANGELOG.md missing entry for version $version"
		return 1
	fi
}

# Function to check changelog has unreleased content
check_changelog_unreleased() {
	local changelog_file="$REPO_ROOT/CHANGELOG.md"

	if [[ ! -f "$changelog_file" ]]; then
		print_warning "CHANGELOG.md not found"
		return 1
	fi

	# Check if [Unreleased] section exists
	if ! grep -q "^\## \[Unreleased\]" "$changelog_file"; then
		print_error "CHANGELOG.md missing [Unreleased] section"
		return 1
	fi

	# Check if there's content under [Unreleased]
	local unreleased_content
	unreleased_content=$(sed -n '/^## \[Unreleased\]/,/^## \[/p' "$changelog_file" | grep -v "^##" | grep -v "^$" | head -5 || true)

	if [[ -z "$unreleased_content" ]]; then
		print_warning "CHANGELOG.md [Unreleased] section is empty"
		return 1
	fi

	print_success "CHANGELOG.md has unreleased content ✓"
	return 0
}

# Function to get releasable commit subjects since last tag
# Excludes release bump commits which are generated by this script.
get_releasable_commit_subjects() {
	local prev_tag
	prev_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	local commits
	if [[ -n "$prev_tag" ]]; then
		commits=$(git log "$prev_tag"..HEAD --pretty=format:"%s" 2>/dev/null)
	else
		commits=$(git log --oneline -20 --pretty=format:"%s" 2>/dev/null)
	fi

	while IFS= read -r commit; do
		[[ -z "$commit" ]] && continue
		[[ "$commit" == chore\(release\):* ]] && continue
		echo "$commit"
	done <<<"$commits"

	return 0
}

# Function to generate changelog preview from commits
generate_changelog_preview() {
	local prev_tag
	prev_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	local version
	version=$(get_current_version)

	echo "## [$version] - $(date +%Y-%m-%d)"
	echo ""

	# Categorize commits
	local added="" changed="" fixed="" security=""

	local commits
	if [[ -n "$prev_tag" ]]; then
		commits=$(git log "$prev_tag"..HEAD --pretty=format:"%s" 2>/dev/null)
	else
		commits=$(git log --oneline -20 --pretty=format:"%s" 2>/dev/null)
	fi

	while IFS= read -r commit; do
		case "$commit" in
		feat:* | feat\(*) added="$added\n- ${commit#feat: }" ;;
		fix:* | fix\(*) fixed="$fixed\n- ${commit#fix: }" ;;
		security:*) security="$security\n- ${commit#security: }" ;;
		refactor:* | docs:* | chore:*) changed="$changed\n- $commit" ;;
		*) ;; # Ignore other commit types
		esac
	done <<<"$commits"

	[[ -n "$added" ]] && echo -e "### Added\n$added\n"
	[[ -n "$changed" ]] && echo -e "### Changed\n$changed\n"
	[[ -n "$fixed" ]] && echo -e "### Fixed\n$fixed\n"
	[[ -n "$security" ]] && echo -e "### Security\n$security\n"

	return 0
}

# Classify a single commit message into a changelog category.
# Appends the formatted entry to the appropriate category variable (passed by name).
# Arguments: commit message
# Outputs: sets caller's added/changed/fixed/security/removed/deprecated via printf to stdout
# Returns category:entry on stdout as "CATEGORY\tentry" for the caller to accumulate.
_classify_commit_to_category() {
	local commit="$1"
	local clean_msg="$commit"

	case "$commit" in
	feat:*)
		clean_msg="${commit#feat: }"
		printf 'added\t- %s\n' "$clean_msg"
		;;
	feat\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^feat([^)]*): //')
		printf 'added\t- %s\n' "$clean_msg"
		;;
	fix:*)
		clean_msg="${commit#fix: }"
		printf 'fixed\t- %s\n' "$clean_msg"
		;;
	fix\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^fix([^)]*): //')
		printf 'fixed\t- %s\n' "$clean_msg"
		;;
	security:*)
		clean_msg="${commit#security: }"
		printf 'security\t- %s\n' "$clean_msg"
		;;
	docs:*)
		clean_msg="${commit#docs: }"
		printf 'changed\t- Documentation: %s\n' "$clean_msg"
		;;
	refactor:*)
		clean_msg="${commit#refactor: }"
		printf 'changed\t- Refactor: %s\n' "$clean_msg"
		;;
	perf:*)
		clean_msg="${commit#perf: }"
		printf 'changed\t- Performance: %s\n' "$clean_msg"
		;;
	BREAKING\ CHANGE:* | breaking:*)
		clean_msg="${commit#BREAKING CHANGE: }"
		clean_msg="${clean_msg#breaking: }"
		printf 'removed\t- **BREAKING**: %s\n' "$clean_msg"
		;;
	deprecate:* | deprecated:*)
		clean_msg="${commit#deprecate: }"
		clean_msg="${clean_msg#deprecated: }"
		printf 'deprecated\t- %s\n' "$clean_msg"
		;;
	test:*)
		clean_msg="${commit#test: }"
		printf 'changed\t- Tests: %s\n' "$clean_msg"
		;;
	test\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^test([^)]*): //')
		printf 'changed\t- Tests: %s\n' "$clean_msg"
		;;
	ci:*)
		clean_msg="${commit#ci: }"
		printf 'changed\t- CI: %s\n' "$clean_msg"
		;;
	ci\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^ci([^)]*): //')
		printf 'changed\t- CI: %s\n' "$clean_msg"
		;;
	build:*)
		clean_msg="${commit#build: }"
		printf 'changed\t- Build: %s\n' "$clean_msg"
		;;
	build\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^build([^)]*): //')
		printf 'changed\t- Build: %s\n' "$clean_msg"
		;;
	chore:*)
		clean_msg="${commit#chore: }"
		printf 'changed\t- Maintenance: %s\n' "$clean_msg"
		;;
	chore\(*\):*)
		clean_msg=$(echo "$commit" | sed 's/^chore([^)]*): //')
		printf 'changed\t- Maintenance: %s\n' "$clean_msg"
		;;
	# Task-ID prefixed commits (e.g., t1741: plan autoresearch, GH#14391: tighten miniflare)
	# These use the commit description which already serves as the issue title.
	t[0-9]*:*)
		clean_msg=$(echo "$commit" | sed 's/^t[0-9][0-9]*[^:]*: //')
		printf 'changed\t- %s\n' "$clean_msg"
		;;
	GH\#[0-9]*:*)
		clean_msg=$(echo "$commit" | sed 's/^GH#[0-9]*: //')
		printf 'changed\t- %s\n' "$clean_msg"
		;;
	*) ;; # Ignore other commit types
	esac
	return 0
}

# Function to generate changelog content from commits (cleaner format)
generate_changelog_content() {
	local prev_tag
	prev_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	local commits
	if [[ -n "$prev_tag" ]]; then
		commits=$(git log "$prev_tag"..HEAD --pretty=format:"%s" 2>/dev/null)
	else
		commits=$(git log --oneline -20 --pretty=format:"%s" 2>/dev/null)
	fi

	# Categorize commits
	local added="" changed="" fixed="" security="" removed="" deprecated=""

	while IFS= read -r commit; do
		[[ -z "$commit" ]] && continue
		[[ "$commit" == chore\(release\):* ]] && continue
		# Skip task ID claim commits (internal bookkeeping, not user-facing)
		[[ "$commit" == "chore: claim t"* ]] && continue
		# Skip bare version bump commits that lack (release) scope
		[[ "$commit" == "chore: bump version to "* ]] && continue

		local category entry classified
		classified=$(_classify_commit_to_category "$commit")
		[[ -z "$classified" ]] && continue

		category="${classified%%	*}"
		entry="${classified#*	}"

		case "$category" in
		added) added="${added}${entry}\n" ;;
		changed) changed="${changed}${entry}\n" ;;
		fixed) fixed="${fixed}${entry}\n" ;;
		security) security="${security}${entry}\n" ;;
		removed) removed="${removed}${entry}\n" ;;
		deprecated) deprecated="${deprecated}${entry}\n" ;;
		esac
	done <<<"$commits"

	# Output in Keep a Changelog order
	[[ -n "$added" ]] && printf "### Added\n\n%b\n" "$added"
	[[ -n "$changed" ]] && printf "### Changed\n\n%b\n" "$changed"
	[[ -n "$deprecated" ]] && printf "### Deprecated\n\n%b\n" "$deprecated"
	[[ -n "$removed" ]] && printf "### Removed\n\n%b\n" "$removed"
	[[ -n "$fixed" ]] && printf "### Fixed\n\n%b\n" "$fixed"
	[[ -n "$security" ]] && printf "### Security\n\n%b\n" "$security"

	return 0
}

# Replace the [Unreleased] section in a changelog file with new version content.
# Reads the changelog, inserts the new version section after [Unreleased], and
# discards old unreleased content.
# Arguments: changelog_file content_file output_file
_replace_unreleased_section() {
	local changelog_file="$1"
	local content_file="$2"
	local output_file="$3"
	local in_unreleased=0

	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "$line" == "## [Unreleased]"* ]]; then
			echo "## [Unreleased]"
			echo ""
			cat "$content_file"
			in_unreleased=1
		elif [[ "$line" == "## ["* ]] && [[ $in_unreleased -eq 1 ]]; then
			# Next version section found, stop skipping
			in_unreleased=0
			echo ""
			echo "$line"
		elif [[ $in_unreleased -eq 0 ]]; then
			echo "$line"
		fi
		# Skip lines while in_unreleased=1 (old unreleased content)
	done <"$changelog_file" >"$output_file"
	return 0
}

# Ensure CHANGELOG.md exists with the standard template.
# Arguments: changelog_file
_ensure_changelog_exists() {
	local changelog_file="$1"

	if [[ -f "$changelog_file" ]]; then
		return 0
	fi

	print_warning "CHANGELOG.md not found, creating new one"
	cat >"$changelog_file" <<'EOF'
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

EOF
	return 0
}

# Function to update CHANGELOG.md with new version
update_changelog() {
	local version="$1"
	local changelog_file="$REPO_ROOT/CHANGELOG.md"
	local today
	today=$(date +%Y-%m-%d)

	_ensure_changelog_exists "$changelog_file"

	# Check if [Unreleased] section exists
	if ! grep -q "^\## \[Unreleased\]" "$changelog_file"; then
		print_error "CHANGELOG.md missing [Unreleased] section"
		return 1
	fi

	# Generate changelog content from commits
	local changelog_content
	changelog_content=$(generate_changelog_content)

	if [[ -z "$changelog_content" ]]; then
		print_warning "No conventional commits found for changelog generation"
		changelog_content="### Changed

- Version bump and maintenance updates
"
	fi

	# Create temp files for the update with trap cleanup
	local temp_file content_file
	temp_file=$(mktemp)
	content_file=$(mktemp)
	# shellcheck disable=SC2064
	trap "rm -f '$temp_file' '$content_file'" EXIT

	# Write the new version section to a temp file (avoids awk multiline issues)
	cat >"$content_file" <<EOF
## [$version] - $today

$changelog_content
EOF

	_replace_unreleased_section "$changelog_file" "$content_file" "$temp_file"

	# Replace original file
	mv "$temp_file" "$changelog_file"
	rm -f "$content_file"
	trap - EXIT

	print_success "Updated CHANGELOG.md: [Unreleased] → [$version] - $today"
	return 0
}

# Function to run preflight quality checks
run_preflight_checks() {
	local bump_type="${1:-}"

	if [[ "$bump_type" == "patch" ]]; then
		run_patch_release_preflight
		return $?
	fi

	print_info "Running preflight quality checks..."

	local preflight_script="$REPO_ROOT/.agents/scripts/linters-local.sh"

	if [[ -f "$preflight_script" ]]; then
		if bash "$preflight_script"; then
			print_success "Preflight checks passed ✓"
			return 0
		else
			print_error "Preflight checks failed"
			return 1
		fi
	else
		print_warning "Preflight script not found, skipping checks"
		return 0
	fi
}

SECRETLINT_CMD=()
PATCH_PREFLIGHT_TMP_DIR=""

secretlint_runtime_works() {
	local -a candidate_cmd=("$@")
	local smoke_file=""

	smoke_file=$(mktemp "$REPO_ROOT/.secretlint-smoke.XXXXXX")
	if [[ -z "$smoke_file" ]]; then
		return 1
	fi

	(
		cd "$REPO_ROOT" || exit 1
		"${candidate_cmd[@]}" "$smoke_file" --format compact >/dev/null 2>&1
	)
	local smoke_exit=$?
	rm -f "$smoke_file"

	if [[ $smoke_exit -ne 0 ]]; then
		return 1
	fi

	return 0
}

secretlint_output_has_runtime_error() {
	local output_file="$1"

	if grep -Eq 'AggregationError|Failed to load rule module|Cannot find module|Cannot create a string longer than|at async file://' "$output_file"; then
		return 0
	fi

	return 1
}

configure_secretlint_command() {
	SECRETLINT_CMD=()
	local -a candidate_cmd=()

	if [[ -x "$REPO_ROOT/node_modules/.bin/secretlint" ]]; then
		candidate_cmd=("$REPO_ROOT/node_modules/.bin/secretlint")
		if secretlint_runtime_works "${candidate_cmd[@]}"; then
			SECRETLINT_CMD=("${candidate_cmd[@]}")
			return 0
		fi
	fi

	if command -v secretlint &>/dev/null; then
		candidate_cmd=(secretlint)
		if secretlint_runtime_works "${candidate_cmd[@]}"; then
			SECRETLINT_CMD=("${candidate_cmd[@]}")
			return 0
		fi
	fi

	if [[ -f "$REPO_ROOT/package.json" ]]; then
		candidate_cmd=(npx -y -p secretlint -p @secretlint/secretlint-rule-preset-recommend secretlint)
		if secretlint_runtime_works "${candidate_cmd[@]}"; then
			SECRETLINT_CMD=("${candidate_cmd[@]}")
			return 0
		fi
	fi

	print_error "No working secretlint runtime found for patch release preflight"
	print_info "Install project dependencies or repair global secretlint rule modules before releasing"
	return 1
}

normalize_secretlint_output() {
	local scan_root="$1"
	local line=""

	while IFS= read -r line; do
		[[ -n "$line" ]] || continue
		line="${line#"$scan_root"/}"
		line="${line#"$scan_root"}"
		line=$(printf '%s\n' "$line" | sed -E 's/: line [0-9]+, col [0-9]+, /: /')
		printf '%s\n' "$line"
	done | sort -u
	return 0
}

capture_secretlint_findings() {
	_save_cleanup_scope
	trap '_run_cleanups' RETURN

	local scan_root="$1"
	local output_file="$2"
	local canonical_scan_root=""
	local raw_output_file=""
	local targets_file=""
	local secretlint_exit=0
	local target_path=""
	local target_output=""
	local target_exit=0

	canonical_scan_root=$(cd "$scan_root" && pwd -P)
	raw_output_file=$(mktemp "$PATCH_PREFLIGHT_TMP_DIR/secretlint-output.XXXXXX")
	if [[ -z "$raw_output_file" ]]; then
		print_error "Failed to allocate temporary file for secretlint output"
		return 1
	fi
	push_cleanup "rm -f '${raw_output_file}'"
	targets_file=$(mktemp "$PATCH_PREFLIGHT_TMP_DIR/secretlint-targets.XXXXXX")
	if [[ -z "$targets_file" ]]; then
		print_error "Failed to allocate temporary file for secretlint targets"
		return 1
	fi
	push_cleanup "rm -f '${targets_file}'"

	(
		cd "$canonical_scan_root" || exit 1
		rg --files --hidden -g '!.git' -0 >"$targets_file"
	)

	if [[ ! -s "$targets_file" ]]; then
		: >"$output_file"
		return 0
	fi

	while IFS= read -r -d '' target_path; do
		target_output=$(
			cd "$canonical_scan_root" || exit 1
			"${SECRETLINT_CMD[@]}" "$target_path" --format compact 2>&1
		)
		target_exit=$?

		if [[ -n "$target_output" ]]; then
			printf '%s\n' "$target_output" >>"$raw_output_file"
		fi

		if [[ $target_exit -ne 0 ]]; then
			if [[ "$target_output" =~ :\ line\ [0-9]+,\ col\ [0-9]+,\  ]]; then
				continue
			fi
			secretlint_exit=1
			break
		fi
	done <"$targets_file"

	if secretlint_output_has_runtime_error "$raw_output_file"; then
		print_error "Secretlint execution failed due to runtime error"
		return 1
	fi

	if [[ $secretlint_exit -ne 0 ]]; then
		print_error "Secretlint execution failed with non-finding output"
		return 1
	fi

	if [[ ! -s "$raw_output_file" ]]; then
		: >"$output_file"
		return 0
	fi

	normalize_secretlint_output "$canonical_scan_root" <"$raw_output_file" >"$output_file"
	return 0
}

cleanup_temp_dir() {
	local target_dir="$1"

	[[ -n "$target_dir" ]] || return 0
	rm -rf "$target_dir"
	return 0
}

# Run secretlint on changed files only (not the entire repo).
# Arguments: baseline_ref changed_files (newline-separated list)
_run_secretlint_on_changed_files() {
	local baseline_ref="$1"
	local changed_files="$2"

	# Scan only CHANGED files with secretlint (not the entire repo).
	# The old approach scanned all ~2000 files twice (current + baseline archive),
	# taking ~22 minutes (0.34s/file x 1962 files x 2). Changed-files-only runs
	# in seconds for typical patch releases with <50 changed files.
	local -a changed_file_list=()
	local cf=""
	while IFS= read -r cf; do
		[[ -n "$cf" ]] || continue
		# Only scan files that exist in the current tree (skip deletions)
		[[ -f "$REPO_ROOT/$cf" ]] && changed_file_list+=("$cf")
	done <<<"$changed_files"

	if [[ ${#changed_file_list[@]} -gt 0 ]]; then
		print_info "Running secretlint on ${#changed_file_list[@]} changed files..."
		local sl_exit_code=0
		local sl_output=""
		sl_output=$(
			cd "$REPO_ROOT" || exit 1
			"${SECRETLINT_CMD[@]}" "${changed_file_list[@]}" --format compact 2>&1
		) || sl_exit_code=$?

		if [[ $sl_exit_code -eq 1 ]]; then
			print_error "Secretlint: findings in changed files since $baseline_ref"
			echo "$sl_output" | head -5
			return 1
		elif [[ $sl_exit_code -ne 0 ]]; then
			print_error "Secretlint execution failed with exit code $sl_exit_code"
			echo "$sl_output" | head -5
			return 1
		fi
		print_success "Secretlint: no findings in changed files since $baseline_ref"
	else
		print_info "Secretlint: no files changed since $baseline_ref"
	fi
	return 0
}

# Run ShellCheck on shell files that changed since baseline_ref.
# Arguments: baseline_ref changed_files (newline-separated list)
_run_shellcheck_on_changed_files() {
	local baseline_ref="$1"
	local changed_files="$2"

	local -a changed_shell_files=()
	local changed_file=""
	while IFS= read -r changed_file; do
		[[ -n "$changed_file" ]] || continue
		case "$changed_file" in
		*.sh)
			changed_shell_files+=("$changed_file")
			;;
		esac
	done <<<"$changed_files"

	if [[ ${#changed_shell_files[@]} -gt 0 ]]; then
		if ! command -v shellcheck &>/dev/null; then
			print_warning "shellcheck not installed (install: brew install shellcheck)"
		else
			print_info "Running ShellCheck on files changed since $baseline_ref..."
			if shellcheck --severity=warning "${changed_shell_files[@]}"; then
				print_success "ShellCheck: changed shell files passed"
			else
				print_error "ShellCheck failed on files changed since $baseline_ref"
				return 1
			fi
		fi
	else
		print_info "ShellCheck: no shell files changed since $baseline_ref"
	fi
	return 0
}

# Run the pre-edit regression test if pre-edit-check.sh or its test was changed.
# Arguments: changed_files (newline-separated list) pre_edit_test_script
_run_pre_edit_regression_test() {
	local changed_files="$1"
	local pre_edit_test_script="$2"

	if [[ "$changed_files" == *".agents/scripts/pre-edit-check.sh"* ]] || [[ "$changed_files" == *".agents/scripts/tests/test-pre-edit-check.sh"* ]]; then
		if [[ ! -x "$pre_edit_test_script" ]]; then
			print_error "Pre-edit regression test missing or not executable: $pre_edit_test_script"
			return 1
		fi

		print_info "Running pre-edit regression test..."
		if bash "$pre_edit_test_script"; then
			print_success "Pre-edit regression test passed"
		else
			print_error "Pre-edit regression test failed"
			return 1
		fi
	fi
	return 0
}

run_patch_release_preflight() {
	local baseline_ref=""
	baseline_ref=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	if [[ -z "$baseline_ref" ]]; then
		print_warning "No previous tag found; falling back to full preflight"
		local preflight_script="$REPO_ROOT/.agents/scripts/linters-local.sh"
		if [[ -f "$preflight_script" ]]; then
			bash "$preflight_script"
			return $?
		fi
		print_warning "Preflight script not found, skipping checks"
		return 0
	fi

	print_info "Running patch release regression preflight against $baseline_ref..."

	local changed_files=""
	changed_files=$(git diff --name-only "$baseline_ref"..HEAD 2>/dev/null || echo "")
	local pre_edit_test_script="$REPO_ROOT/.agents/scripts/tests/test-pre-edit-check.sh"

	if ! configure_secretlint_command; then
		return 1
	fi

	local tmp_dir=""
	tmp_dir=$(mktemp -d)
	PATCH_PREFLIGHT_TMP_DIR="$tmp_dir"
	trap 'cleanup_temp_dir "$PATCH_PREFLIGHT_TMP_DIR"; PATCH_PREFLIGHT_TMP_DIR=""' RETURN

	if ! _run_secretlint_on_changed_files "$baseline_ref" "$changed_files"; then
		return 1
	fi

	if ! _run_shellcheck_on_changed_files "$baseline_ref" "$changed_files"; then
		return 1
	fi

	if ! _run_pre_edit_regression_test "$changed_files" "$pre_edit_test_script"; then
		return 1
	fi

	print_success "Patch release regression preflight passed"
	return 0
}

# Function to validate version consistency across files
# Delegates to the standalone validator script for single source of truth
validate_version_consistency() {
	local expected_version="$1"
	local validator_script="${REPO_ROOT}/.agents/scripts/validate-version-consistency.sh"

	print_info "Validating version consistency across files..."

	if [[ -f "$validator_script" ]]; then
		# Use the standalone validator (single source of truth)
		bash "$validator_script" "$expected_version"
		return $?
	else
		# Fallback: basic validation if standalone script not found
		print_warning "Standalone validator not found, using basic validation"

		local errors=0

		# Check VERSION file
		if [[ -f "$VERSION_FILE" ]]; then
			local version_file_content
			version_file_content=$(cat "$VERSION_FILE")
			if [[ "$version_file_content" != "$expected_version" ]]; then
				print_error "VERSION file contains '$version_file_content', expected '$expected_version'"
				errors=$((errors + 1))
			else
				print_success "VERSION file: $expected_version ✓"
			fi
		else
			print_error "VERSION file not found"
			errors=$((errors + 1))
		fi

		if [[ $errors -eq 0 ]]; then
			print_success "Basic version validation passed: $expected_version"
			return 0
		else
			print_error "Found $errors version inconsistencies"
			return 1
		fi
	fi
}

# Update the README.md version badge (hardcoded or dynamic).
# All output goes to stderr. Returns 0 on success, 1 on failure.
# Increments the caller's errors counter via stdout ("1" on failure, "0" on success).
_update_readme_version_badge() {
	local new_version="$1"
	local dynamic_badge_pattern="img.shields.io/github/v/release"
	local hardcoded_badge_pattern="Version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue"

	if [[ ! -f "$REPO_ROOT/README.md" ]]; then
		print_warning "README.md not found, skipping version badge update" >&2
		return 0
	fi

	if grep -q "$dynamic_badge_pattern" "$REPO_ROOT/README.md"; then
		# Dynamic badge - no update needed, GitHub handles it automatically
		print_success "README.md uses dynamic GitHub release badge (no update needed)" >&2
	elif grep -q "$hardcoded_badge_pattern" "$REPO_ROOT/README.md"; then
		# Hardcoded badge - update it
		sed_inplace "s/$hardcoded_badge_pattern/Version-$new_version-blue/" "$REPO_ROOT/README.md"
		if grep -q "Version-$new_version-blue" "$REPO_ROOT/README.md"; then
			print_success "Updated README.md version badge to $new_version" >&2
		else
			print_error "Failed to update README.md version badge"
			return 1
		fi
	else
		# No version badge found - that's okay, just warn
		print_warning "README.md has no version badge (consider adding dynamic GitHub release badge)" >&2
	fi
	return 0
}

# Update the Homebrew formula URL to the new version.
# SHA256 is updated separately by CI publish-packages.yml.
# All output goes to stderr. Returns 0 on success, 1 on failure.
_update_homebrew_formula() {
	local new_version="$1"
	local formula_file="$REPO_ROOT/homebrew/aidevops.rb"

	if [[ ! -f "$formula_file" ]]; then
		return 0
	fi

	sed_inplace "s|url \"https://github.com/marcusquinn/aidevops/archive/refs/tags/v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.tar\.gz\"|url \"https://github.com/marcusquinn/aidevops/archive/refs/tags/v${new_version}.tar.gz\"|" "$formula_file"

	if grep -q "v${new_version}.tar.gz" "$formula_file"; then
		print_success "Updated homebrew/aidevops.rb version URL" >&2
	else
		print_error "Failed to update homebrew/aidevops.rb"
		return 1
	fi
	return 0
}

# Update the Claude Code plugin marketplace.json version field.
# All output goes to stderr. Returns 0 on success, 1 on failure.
_update_claude_plugin_version() {
	local new_version="$1"
	local plugin_file="$REPO_ROOT/.claude-plugin/marketplace.json"

	if [[ ! -f "$plugin_file" ]]; then
		return 0
	fi

	sed_inplace "s/\"version\": *\"[^\"]*\"/\"version\": \"$new_version\"/" "$plugin_file"

	if grep -q "\"version\": \"$new_version\"" "$plugin_file"; then
		print_success "Updated .claude-plugin/marketplace.json" >&2
	else
		print_error "Failed to update .claude-plugin/marketplace.json"
		return 1
	fi
	return 0
}

# Update the VERSION file with the new version string.
# All output goes to stderr. Returns 0 on success, 1 on failure.
_update_version_file() {
	local new_version="$1"

	if [[ ! -f "$VERSION_FILE" ]]; then
		return 0
	fi

	echo "$new_version" >"$VERSION_FILE"
	if [[ "$(cat "$VERSION_FILE")" == "$new_version" ]]; then
		print_success "Updated VERSION file" >&2
		return 0
	fi

	print_error "Failed to update VERSION file"
	return 1
}

# Update the package.json version field.
# All output goes to stderr. Returns 0 on success, 1 on failure.
_update_package_json_version() {
	local new_version="$1"

	if [[ ! -f "$REPO_ROOT/package.json" ]]; then
		return 0
	fi

	sed_inplace "s/\"version\": *\"[^\"]*\"/\"version\": \"$new_version\"/" "$REPO_ROOT/package.json"
	if grep -q "\"version\": \"$new_version\"" "$REPO_ROOT/package.json"; then
		print_success "Updated package.json" >&2
		return 0
	fi

	print_error "Failed to update package.json"
	return 1
}

# Update the sonar-project.properties version field.
# All output goes to stderr. Returns 0 on success, 1 on failure.
_update_sonar_version() {
	local new_version="$1"

	if [[ ! -f "$REPO_ROOT/sonar-project.properties" ]]; then
		return 0
	fi

	sed_inplace "s/sonar\.projectVersion=.*/sonar.projectVersion=$new_version/" "$REPO_ROOT/sonar-project.properties"
	if grep -q "sonar.projectVersion=$new_version" "$REPO_ROOT/sonar-project.properties"; then
		print_success "Updated sonar-project.properties" >&2
		return 0
	fi

	print_error "Failed to update sonar-project.properties"
	return 1
}

# Function to update version in files
# All diagnostic output goes to stderr so callers that capture stdout
# as a version string (e.g. auto-version-bump.sh) are not polluted.
update_version_in_files() {
	local new_version="$1"
	local errors=0

	print_info "Updating version references in files..." >&2

	_update_version_file "$new_version" || errors=$((errors + 1))
	_update_package_json_version "$new_version" || errors=$((errors + 1))
	_update_sonar_version "$new_version" || errors=$((errors + 1))

	update_script_version_reference "$REPO_ROOT/setup.sh" "$new_version" "setup.sh" || errors=$((errors + 1))
	update_script_version_reference "$REPO_ROOT/aidevops.sh" "$new_version" "aidevops.sh" || errors=$((errors + 1))

	_update_readme_version_badge "$new_version" || errors=$((errors + 1))
	_update_homebrew_formula "$new_version" || errors=$((errors + 1))
	_update_claude_plugin_version "$new_version" || errors=$((errors + 1))

	if [[ $errors -gt 0 ]]; then
		print_error "Failed to update $errors file(s)"
		return 1
	fi

	print_success "All version files updated to $new_version" >&2
	return 0
}

update_script_version_reference() {
	local script_path="$1"
	local new_version="$2"
	local script_name="$3"

	if [[ ! -f "$script_path" ]]; then
		return 0
	fi

	sed_inplace "s/# Version: .*/# Version: $new_version/" "$script_path"
	if grep -Fq "# Version: $new_version" "$script_path"; then
		print_success "Updated $script_name" >&2
		return 0
	fi

	print_error "Failed to update $script_name"
	return 1
}

# Function to verify local branch is in sync with remote
# Prevents release failures when local has diverged (e.g., after squash merge)
verify_remote_sync() {
	local branch="$1"
	branch="${branch:-main}"

	cd "$REPO_ROOT" || exit 1

	# Verify we're actually on the expected branch
	local current_branch
	current_branch=$(git branch --show-current 2>/dev/null)
	if [[ "$current_branch" != "$branch" ]]; then
		print_error "Not on $branch branch (currently on: ${current_branch:-detached HEAD})"
		print_info "Switch to $branch first: git checkout $branch"
		return 1
	fi

	print_info "Verifying local/$branch is in sync with origin/$branch..."

	# Fetch latest from remote
	if ! git fetch origin "$branch" --quiet 2>/dev/null; then
		print_warning "Could not fetch from remote - proceeding without sync check"
		return 0
	fi

	local local_sha
	local_sha=$(git rev-parse "$branch" 2>/dev/null)
	local remote_sha
	remote_sha=$(git rev-parse "origin/$branch" 2>/dev/null)

	if [[ -z "$local_sha" || -z "$remote_sha" ]]; then
		print_warning "Could not determine local/remote SHA - proceeding without sync check"
		return 0
	fi

	if [[ "$local_sha" != "$remote_sha" ]]; then
		# Check relationship: behind, ahead, or diverged
		if git merge-base --is-ancestor "$local_sha" "$remote_sha" 2>/dev/null; then
			# Local is behind remote - auto-pull with rebase
			print_info "Local $branch is behind origin/$branch, pulling..."
			if git pull --rebase origin "$branch" --quiet 2>/dev/null; then
				print_success "Auto-pulled latest changes from origin/$branch"
				return 0
			else
				print_error "Failed to auto-pull. Manual intervention required."
				print_info "Fix with: git pull --rebase origin $branch"
				return 1
			fi
		elif git merge-base --is-ancestor "$remote_sha" "$local_sha" 2>/dev/null; then
			# Local is ahead of remote - this is fine for release, just inform
			print_info "Local $branch is ahead of origin/$branch (unpushed commits)"
			print_info "This is expected if you have local commits ready to release."
			return 0
		else
			# Truly diverged - cannot auto-fix
			print_error "Local $branch has diverged from origin/$branch"
			print_info "  Local:  $local_sha"
			print_info "  Remote: $remote_sha"
			echo ""
			print_info "This commonly happens after a squash merge on GitHub."
			print_info "Inspect the divergence before deciding how to proceed:"
			print_info "  git log --oneline origin/$branch...$branch"
			print_info "If local commits are already merged upstream (squash merge), reset is safe:"
			print_info "  git fetch origin && git reset --hard origin/$branch"
			print_info "If local commits are NOT yet merged, rebase instead:"
			print_info "  git fetch origin && git rebase origin/$branch"
			return 1
		fi
	fi

	print_success "Local $branch is in sync with origin/$branch"
	return 0
}

# Function to check for uncommitted changes
check_working_tree_clean() {
	local uncommitted
	uncommitted=$(git status --porcelain 2>/dev/null)

	if [[ -n "$uncommitted" ]]; then
		print_error "Working tree has uncommitted changes:"
		echo "$uncommitted" | head -20
		echo ""
		print_info "Options:"
		print_info "  1. Commit your changes first: git add -A && git commit -m 'your message'"
		print_info "  2. Stash changes: git stash"
		print_info "  3. Use --allow-dirty to release anyway (not recommended)"
		return 1
	fi
	return 0
}

# Function to extract task IDs from commit messages since last tag
# Only extracts from commits that indicate task COMPLETION, not mere mentions
# Completion patterns:
#   - Conventional commits with task scope: feat(t001):, fix(t002):, docs(t003):
#   - Explicit completion phrases: "mark t001 done", "complete t002", "closes t003"
#   - Multi-task with explicit marker: "mark t001, t002 done" (tasks before "done")
extract_task_ids_from_commits() {
	local prev_tag
	prev_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	local commits
	if [[ -n "$prev_tag" ]]; then
		commits=$(git log "$prev_tag"..HEAD --pretty=format:"%s" 2>/dev/null)
	else
		commits=$(git log --oneline -50 --pretty=format:"%s" 2>/dev/null)
	fi

	local -a task_ids=()

	while IFS= read -r commit; do
		[[ -z "$commit" ]] && continue

		# Pattern 1: Conventional commits with task ID in scope
		# e.g., feat(t001):, fix(t002):, docs(t003.1):, refactor(t004):
		if [[ "$commit" =~ ^(feat|fix|docs|refactor|perf|test|chore|style|build|ci)\((t[0-9]{3}(\.[0-9]+)*)\): ]]; then
			task_ids+=("${BASH_REMATCH[2]}")
		fi

		# Pattern 2: "mark tXXX done/complete" - extract task IDs between "mark" and "done/complete"
		# e.g., "mark t004, t048, t069 done" -> t004, t048, t069
		if [[ "$commit" =~ mark[[:space:]]+(.*)[[:space:]]+(done|complete) ]]; then
			local segment="${BASH_REMATCH[1]}"
			local id
			while IFS= read -r id; do
				[[ -n "$id" ]] || continue
				task_ids+=("$id")
			done < <(printf '%s\n' "$segment" | grep -oE 't[0-9]{3}(\.[0-9]+)*' || true)
		fi

		# Pattern 3: "complete/completes/closes tXXX" - task ID immediately after keyword
		# e.g., "complete t037", "closes t001"
		if [[ "$commit" =~ (^|[^[:alnum:]_])(completes?|closes?)[[:space:]]+(t[0-9]{3}(\.[0-9]+)*)([^[:alnum:]_]|$) ]]; then
			task_ids+=("${BASH_REMATCH[3]}")
		fi

		# Pattern 4: "tXXX complete/done/finished" - task ID before completion word
		# e.g., "t001 complete", "t002 done"
		if [[ "$commit" =~ (t[0-9]{3}(\.[0-9]+)*)[[:space:]]+(complete|done|finished)($|[^[:alnum:]_]) ]]; then
			task_ids+=("${BASH_REMATCH[1]}")
		fi

	done <<<"$commits"

	# Deduplicate and sort
	if [[ ${#task_ids[@]} -eq 0 ]]; then
		return 0
	fi

	printf '%s\n' "${task_ids[@]}" | grep -E '^t[0-9]{3}(\.[0-9]+)*$' | sort -u
	return 0
}

# Function to find the PR number associated with a task ID from commit messages (t1004)
# Searches commits since last tag for PR references like (#NNN) in commits mentioning the task
# Falls back to gh CLI search if no PR found in commit messages
find_pr_for_task_from_commits() {
	local task_id="$1"

	local prev_tag
	prev_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

	local commits
	if [[ -n "$prev_tag" ]]; then
		commits=$(git log "$prev_tag"..HEAD --pretty=format:"%s" 2>/dev/null)
	else
		commits=$(git log --oneline -50 --pretty=format:"%s" 2>/dev/null)
	fi

	# Search commit messages containing this task ID for (#NNN) PR references
	local pr_number=""
	while IFS= read -r commit; do
		[[ -z "$commit" ]] && continue
		if [[ "$commit" == *"$task_id"* ]]; then
			pr_number=$(echo "$commit" | grep -oE '#[0-9]+' | head -1 | tr -d '#')
			if [[ -n "$pr_number" ]]; then
				break
			fi
		fi
	done <<<"$commits"

	# Fallback: try gh CLI to find merged PR for this task
	if [[ -z "$pr_number" ]] && command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
		pr_number=$(gh pr list --state merged --search "$task_id" --limit 1 --json number --jq '.[0].number' 2>/dev/null || true)
	fi

	echo "$pr_number"
	return 0
}

# Mark a single task as complete in TODO.md.
# Changes [ ] to [x], adds proof-log (pr:#NNN or verified:date) and completed: timestamp.
# Arguments: task_id todo_file today_short
# Returns: 0 if marked, 1 if already complete, 2 if not found
_mark_single_task_complete() {
	local task_id="$1"
	local todo_file="$2"
	local today_short="$3"

	# Build regex patterns (avoids shellcheck SC1087 false positive with [[:space:]])
	local unchecked_pattern="^[[:space:]]*- \\[ \\] ${task_id}[[:space:]]"
	local checked_pattern="^[[:space:]]*- \\[x\\] ${task_id}[[:space:]]"

	if grep -qE "$unchecked_pattern" "$todo_file"; then
		local escaped_id
		escaped_id=$(echo "$task_id" | sed 's/\./\\./g')

		# Discover PR number for proof-log (t1004)
		local pr_number=""
		pr_number=$(find_pr_for_task_from_commits "$task_id")

		# Build proof-log: pr:#NNN if PR found, otherwise verified:date
		local proof_log=""
		if [[ -n "$pr_number" ]]; then
			proof_log=" pr:#${pr_number}"
		else
			proof_log=" verified:${today_short}"
		fi

		local sed_unchecked_pattern="^[[:space:]]*- \\[ \\] ${escaped_id}[[:space:]]"

		# Check if line already has completed: field
		if grep -E "$sed_unchecked_pattern" "$todo_file" | grep -q "completed:"; then
			sed_inplace "s/^\\([[:space:]]*\\)- \\[ \\] \\(${escaped_id}[[:space:]].*\\)\$/\\1- [x] \\2${proof_log}/" "$todo_file"
		else
			sed_inplace "s/^\\([[:space:]]*\\)- \\[ \\] \\(${escaped_id}[[:space:]].*\\)\$/\\1- [x] \\2${proof_log} completed:$today_short/" "$todo_file"
		fi

		print_success "Marked $task_id as complete (${proof_log# })"
		return 0
	elif grep -qE "$checked_pattern" "$todo_file"; then
		print_info "Task $task_id already marked complete"
		return 1
	else
		print_warning "Task $task_id not found in TODO.md (may be subtask or already moved)"
		return 2
	fi
}

# Function to auto-mark tasks complete in TODO.md based on commit messages
# Parses commits since last tag for task IDs and marks them complete
# Writes pr:#NNN proof-log when a PR is discoverable, otherwise verified:YYYY-MM-DD (t1004)
auto_mark_tasks_complete() {
	local todo_file="$REPO_ROOT/TODO.md"
	local today_short
	today_short=$(date +%Y-%m-%d)

	if [[ ! -f "$todo_file" ]]; then
		print_warning "TODO.md not found, skipping task auto-completion"
		return 0
	fi

	print_info "Scanning commits for task IDs to auto-mark complete..."

	local task_ids
	task_ids=$(extract_task_ids_from_commits)

	if [[ -z "$task_ids" ]]; then
		print_info "No task IDs found in commits since last release"
		return 0
	fi

	local count=0
	local marked_tasks=""

	while IFS= read -r task_id; do
		[[ -z "$task_id" ]] && continue

		if _mark_single_task_complete "$task_id" "$todo_file" "$today_short"; then
			count=$((count + 1))
			marked_tasks="$marked_tasks $task_id"
		fi
	done <<<"$task_ids"

	if [[ $count -gt 0 ]]; then
		print_success "Auto-marked $count task(s) complete:$marked_tasks"
	fi

	return 0
}

# Function to commit version changes
commit_version_changes() {
	local version="$1"

	cd "$REPO_ROOT" || exit 1

	print_info "Committing version changes..."

	# Stage all version-related files (including CHANGELOG.md, TODO.md, Homebrew formula, and Claude plugin)
	git add VERSION package.json README.md setup.sh aidevops.sh sonar-project.properties CHANGELOG.md TODO.md homebrew/aidevops.rb .claude-plugin/marketplace.json 2>/dev/null

	# Check if there are changes to commit
	if git diff --cached --quiet; then
		print_info "No version changes to commit"
		return 0
	fi

	if git commit -m "chore(release): bump version to $version"; then
		print_success "Committed version changes"
		return 0
	else
		print_error "Failed to commit version changes"
		return 1
	fi
}

# Function to push changes and tags
push_changes() {
	cd "$REPO_ROOT" || exit 1

	print_info "Pushing changes to remote..."

	# Use --atomic to ensure commit and tag are pushed together (all-or-nothing)
	if git push --atomic origin main --tags; then
		print_success "Pushed changes and tags to remote"
		return 0
	else
		print_error "Failed to push to remote"
		return 1
	fi
}

# Function to create git tag
create_git_tag() {
	local version="$1"
	local tag_name="v$version"

	print_info "Creating git tag: $tag_name"

	cd "$REPO_ROOT" || exit 1

	# Guard: abort if tag already exists locally or on remote
	if git show-ref --tags "$tag_name" &>/dev/null; then
		local existing_sha
		existing_sha=$(git rev-parse "$tag_name^{}" 2>/dev/null || git rev-parse "$tag_name" 2>/dev/null)
		print_error "Tag $tag_name already exists locally (points to $existing_sha)"
		print_info "This indicates a partial or concurrent release. Diagnose with:"
		print_info "  git show $tag_name"
		print_info "  gh release view $tag_name"
		print_info "If the tag is orphaned (no matching GitHub release), delete it and retry:"
		print_info "  git tag -d $tag_name && git push origin :refs/tags/$tag_name"
		return 1
	fi

	# Also check remote tags to catch tags pushed by a concurrent run
	git ls-remote -q --exit-code --tags origin "refs/tags/$tag_name" >/dev/null 2>&1
	local remote_tag_exit=$?
	if [ $remote_tag_exit -eq 0 ]; then
		print_error "Tag $tag_name already exists on remote origin"
		print_info "A concurrent release run may have pushed this tag. Diagnose with:"
		print_info "  git fetch --tags && git show $tag_name"
		print_info "  gh release view $tag_name"
		return 1
	fi

	if git tag -a "$tag_name" -m "Release $tag_name - AI DevOps Framework"; then
		print_success "Created git tag: $tag_name"
		return 0
	else
		print_error "Failed to create git tag"
		return 1
	fi
	return 0
}

# Function to create GitHub release
create_github_release() {
	local version="$1"
	local tag_name="v$version"

	print_info "Creating GitHub release: $tag_name"

	# Try GitHub CLI first
	if command -v gh &>/dev/null && gh auth status &>/dev/null; then
		print_info "Using GitHub CLI for release creation"

		# Guard: check if GitHub release already exists for this tag
		if gh release view "$tag_name" &>/dev/null; then
			print_warning "GitHub release $tag_name already exists — skipping creation"
			print_info "To view the existing release: gh release view $tag_name"
			return 0
		fi

		# Generate release notes based on version
		local release_notes
		release_notes=$(generate_release_notes "$version")

		# Create GitHub release
		if gh release create "$tag_name" \
			--title "$tag_name - AI DevOps Framework" \
			--notes "$release_notes" \
			--latest; then
			print_success "Created GitHub release: $tag_name"
			return 0
		else
			print_error "Failed to create GitHub release with GitHub CLI"
			return 1
		fi
	else
		# GitHub CLI not available
		print_warning "GitHub release creation skipped - GitHub CLI not available"
		print_info "To enable GitHub releases:"
		print_info "1. Install GitHub CLI: brew install gh (macOS)"
		print_info "2. Authenticate: gh auth login"
		return 0
	fi
	return 0
}

run_post_release_agent_sync() {
	local sync_repo_root="${AIDEVOPS_SYNC_REPO_ROOT:-$REPO_ROOT}"
	local remote_url
	remote_url=$(git -C "$sync_repo_root" remote get-url origin 2>/dev/null || echo "")

	if [[ "$remote_url" != *"marcusquinn/aidevops"* ]]; then
		return 0
	fi

	local deploy_script="${AIDEVOPS_SYNC_DEPLOY_SCRIPT:-$sync_repo_root/.agents/scripts/deploy-agents-on-merge.sh}"
	if [[ ! -f "$deploy_script" ]]; then
		print_warning "Post-release sync skipped: deploy script not found at $deploy_script"
		return 0
	fi

	print_info "Running post-release aidevops agent sync..."
	local sync_output=""
	local sync_exit=0
	sync_output=$(bash "$deploy_script" --repo "$sync_repo_root" --quiet 2>&1) || sync_exit=$?

	if [[ "$sync_exit" -eq 0 || "$sync_exit" -eq 2 ]]; then
		print_success "Post-release aidevops agent sync completed"
		return 0
	fi

	print_warning "Post-release aidevops agent sync failed (non-blocking): $sync_output"
	return 0
}

# Function to generate release notes
generate_release_notes() {
	local version="$1"
	# Parse version components (reserved for version-specific logic)
	# shellcheck disable=SC2034
	local major minor patch
	IFS='.' read -r major minor patch <<<"$version"

	cat <<EOF
## AI DevOps Framework v$version

### Installation

\`\`\`bash
# npm (recommended)
npm install -g aidevops && aidevops update

# Homebrew
brew install marcusquinn/tap/aidevops && aidevops update

# curl
bash <(curl -fsSL https://aidevops.sh/install)
\`\`\`

### What's New

See [CHANGELOG.md](CHANGELOG.md) for detailed changes.

### Quick Start

\`\`\`bash
# Check installation
aidevops status

# Initialize in a project
aidevops init

# Update framework + projects
aidevops update

# List registered projects
aidevops repos
\`\`\`

### Documentation

- **[Setup Guide](README.md)**: Complete framework setup
- **[User Guide](.agents/AGENTS.md)**: AI assistant integration
- **[API Integrations](.agents/aidevops/api-integrations.md)**: Service APIs

### Links

- **Website**: https://aidevops.sh
- **Repository**: https://github.com/marcusquinn/aidevops
- **Issues**: https://github.com/marcusquinn/aidevops/issues

---

**Full Changelog**: https://github.com/marcusquinn/aidevops/compare/v1.0.0...v$version
EOF
	return 0
}

# Handle the "bump" action: bump version and update all files.
# Arguments: bump_type [major|minor|patch]
_main_bump() {
	local bump_type="$1"

	if [[ -z "$bump_type" ]]; then
		print_error "Bump type required. Usage: $0 bump [major|minor|patch]"
		exit 1
	fi

	local current_version
	current_version=$(get_current_version)
	print_info "Current version: $current_version"

	local new_version
	new_version=$(bump_version "$bump_type")

	if [[ $? -eq 0 ]]; then
		print_success "Bumped version: $current_version → $new_version"
		if ! update_version_in_files "$new_version"; then
			print_error "Failed to update version in all files"
			print_info "Run validation to check: $0 validate"
			exit 1
		fi
		echo "$new_version"
	else
		exit 1
	fi
	return 0
}

# Check changelog state before release; exit if nothing to release.
# Arguments: force_flag
_release_check_changelog() {
	local force_flag="$1"

	if ! check_changelog_unreleased; then
		local releasable_commits
		releasable_commits=$(get_releasable_commit_subjects)

		if [[ -n "$releasable_commits" ]]; then
			print_warning "CHANGELOG.md [Unreleased] is empty; proceeding with auto-generated changelog from commit history"
			print_info "Detected releasable commits since last tag:"
			local listed_count=0
			while IFS= read -r commit_subject; do
				[[ -z "$commit_subject" ]] && continue
				print_info "  - $commit_subject"
				listed_count=$((listed_count + 1))
				if [[ "$listed_count" -ge 5 ]]; then
					break
				fi
			done <<<"$releasable_commits"
		else
			if [[ "$force_flag" != "--force" ]]; then
				print_error "CHANGELOG.md [Unreleased] is empty and no releasable commits were found since last tag"
				print_info "Nothing meaningful to release. Add commits or use --force to bypass"
				exit 1
			else
				print_warning "Bypassing changelog and empty-commit checks with --force"
			fi
		fi
	fi
	return 0
}

# Perform the version bump, file updates, tag, push, and GitHub release.
# Arguments: bump_type new_version
_release_execute() {
	local bump_type="$1"
	local new_version="$2"
	local tag_name="v$new_version"

	# Guard: detect partial release state before making any changes.
	# A tag without a matching GitHub release indicates a prior failed run.
	# Abort early with clear diagnostics rather than creating a duplicate tag.
	git ls-remote -q --exit-code --tags origin "refs/tags/$tag_name" >/dev/null 2>&1
	local preflight_remote_exit=$?
	if git show-ref --tags "$tag_name" &>/dev/null || [ $preflight_remote_exit -eq 0 ]; then
		print_error "PARTIAL RELEASE STATE DETECTED: tag $tag_name already exists"
		print_info ""
		print_info "Diagnosis:"
		print_info "  git show $tag_name                    # inspect the existing tag"
		print_info "  gh release view $tag_name             # check if GitHub release exists"
		print_info "  git log $tag_name --oneline -5        # see what the tag points to"
		print_info ""
		print_info "Recovery options:"
		print_info "  A) Tag exists + GitHub release exists → already released, nothing to do"
		print_info "  B) Tag exists + no GitHub release    → run: $0 github-release"
		print_info "  C) Tag is orphaned/wrong commit      → delete and retry:"
		print_info "       git tag -d $tag_name"
		print_info "       git push origin :refs/tags/$tag_name"
		print_info "       $0 release $bump_type"
		exit 1
	fi

	print_info "Updating version references in files..."
	if ! update_version_in_files "$new_version"; then
		print_error "Failed to update version in all files. Aborting release."
		print_info "The VERSION file may have been updated. Run validation to check:"
		print_info "  $0 validate"
		exit 1
	fi

	print_info "Updating CHANGELOG.md..."
	if ! update_changelog "$new_version"; then
		print_warning "Failed to update CHANGELOG.md automatically"
	fi

	# Auto-mark tasks complete based on commit messages
	auto_mark_tasks_complete

	print_info "Validating version consistency..."
	if validate_version_consistency "$new_version"; then
		print_success "Version validation passed"
		commit_version_changes "$new_version"
		if ! create_git_tag "$new_version"; then
			print_error "Aborting release: tag creation failed (see above for diagnosis)"
			exit 1
		fi
		if ! push_changes; then
			# --atomic push failed: tag was NOT pushed to remote.
			# Check whether a concurrent run already pushed the tag before rolling back.
			git ls-remote -q --exit-code --tags origin "refs/tags/v$new_version" >/dev/null 2>&1
			local push_fail_remote_exit=$?
			if [ $push_fail_remote_exit -eq 0 ]; then
				print_warning "Push failed but tag v$new_version already exists on remote (concurrent release?)"
				print_info "Deleting local tag to avoid divergence. Check remote state:"
				git tag -d "v$new_version" 2>/dev/null || true
				print_info "  gh release view v$new_version   # check if GitHub release was created"
				print_info "  git fetch --tags && git log v$new_version --oneline -3"
				exit 1
			fi
			# Safe to roll back: tag is local-only
			print_warning "Rolling back local tag v$new_version due to push failure"
			git tag -d "v$new_version" 2>/dev/null || true
			echo ""
			print_info "The version commit exists locally. To complete the release:"
			print_info "  1. Fix the issue (e.g., git fetch origin && git rebase origin/main)"
			print_info "  2. Re-create tag: git tag -a v$new_version -m 'Release v$new_version'"
			print_info "  3. Push: git push --atomic origin main --tags"
			print_info "  4. Create release: $0 github-release"
			exit 1
		fi
		create_github_release "$new_version"
		run_post_release_agent_sync
		print_success "Release $new_version created successfully!"
	else
		print_error "Version validation failed. Please fix inconsistencies before creating release."
		exit 1
	fi
	return 0
}

# Handle the "release" action: full release pipeline.
# Arguments: bump_type [flags...] (all positional args from main, starting at $1=bump_type)
_main_release() {
	local bump_type="$1"
	shift

	if [[ -z "$bump_type" ]]; then
		print_error "Bump type required. Usage: $0 release [major|minor|patch]"
		exit 1
	fi

	# Parse flags (can be in any order after bump_type)
	local force_flag=""
	local skip_preflight=""
	local allow_dirty=""
	for arg in "$@"; do
		case "$arg" in
		"--force") force_flag="--force" ;;
		"--skip-preflight") skip_preflight="--skip-preflight" ;;
		"--allow-dirty") allow_dirty="--allow-dirty" ;;
		*) ;; # Ignore unknown flags
		esac
	done

	print_info "Creating release with $bump_type version bump..."

	# Verify local branch is in sync with remote (prevents post-squash-merge failures)
	if ! verify_remote_sync "main"; then
		if [[ "$force_flag" != "--force" ]]; then
			print_error "Cannot release when local/remote are out of sync."
			print_info "Use --force to bypass (not recommended)"
			exit 1
		else
			print_warning "Bypassing remote sync check with --force"
		fi
	fi

	# Check for uncommitted changes
	if [[ "$allow_dirty" != "--allow-dirty" ]]; then
		if ! check_working_tree_clean; then
			print_error "Cannot release with uncommitted changes."
			print_info "Commit your changes first, or use --allow-dirty to bypass (not recommended)"
			exit 1
		fi
	else
		print_warning "Releasing with uncommitted changes (--allow-dirty)"
	fi

	# Run preflight checks unless skipped
	if [[ "$skip_preflight" != "--skip-preflight" ]]; then
		if ! run_preflight_checks "$bump_type"; then
			print_error "Preflight checks failed. Fix issues or use --skip-preflight to bypass."
			exit 1
		fi
	else
		print_warning "Skipping preflight checks with --skip-preflight"
	fi

	_release_check_changelog "$force_flag"

	local new_version
	new_version=$(bump_version "$bump_type")

	if [[ $? -eq 0 ]]; then
		_release_execute "$bump_type" "$new_version"
	else
		exit 1
	fi
	return 0
}

# Print usage/help text.
_main_usage() {
	echo "AI DevOps Framework Version Manager"
	echo ""
	echo "Usage: $0 [action] [options]"
	echo ""
	echo "Actions:"
	echo "  get                           Get current version"
	echo "  bump [major|minor|patch]      Bump version"
	echo "  tag                           Create git tag for current version"
	echo "  github-release                Create GitHub release for current version"
	echo "  release [major|minor|patch]   Bump version, update files, create tag and GitHub release"
	echo "  preflight [major|minor|patch] Run release preflight checks only"
	echo "  validate                      Validate version consistency across all files"
	echo "  changelog-check               Check CHANGELOG.md has entry for current version"
	echo "  changelog-preview             Generate changelog entry from commits since last tag"
	echo "  auto-mark-tasks               Auto-mark tasks complete based on commit messages"
	echo "  list-task-ids                 List task IDs found in commits since last release"
	echo ""
	echo "Options:"
	echo "  --force                       Bypass changelog check (use with release)"
	echo "  --skip-preflight              Bypass quality checks (use with release)"
	echo ""
	echo "Examples:"
	echo "  $0 get"
	echo "  $0 bump minor"
	echo "  $0 release patch"
	echo "  $0 release minor --force"
	echo "  $0 release patch --skip-preflight"
	echo "  $0 release patch --force --skip-preflight"
	echo "  $0 github-release"
	echo "  $0 validate"
	echo "  $0 changelog-check"
	echo "  $0 changelog-preview"
	return 0
}

# Main function
main() {
	local action="${1:-}"
	local bump_type="${2:-}"

	case "$action" in
	"get")
		get_current_version
		;;
	"bump")
		_main_bump "$bump_type"
		;;
	"tag")
		local version
		version=$(get_current_version)
		create_git_tag "$version"
		;;
	"release")
		_main_release "$bump_type" "${@:3}"
		;;
	"github-release")
		local version
		version=$(get_current_version)
		create_github_release "$version"
		;;
	"validate")
		local version
		version=$(get_current_version)
		validate_version_consistency "$version"
		;;
	"preflight")
		if [[ -z "$bump_type" ]]; then
			print_error "Bump type required. Usage: $0 preflight [major|minor|patch]"
			exit 1
		fi
		run_preflight_checks "$bump_type"
		;;
	"changelog-check")
		local version
		version=$(get_current_version)
		print_info "Checking CHANGELOG.md for version $version..."
		if check_changelog_version "$version"; then
			print_success "CHANGELOG.md is in sync with VERSION"
		else
			print_error "CHANGELOG.md is out of sync with VERSION ($version)"
			print_info "Run: $0 changelog-preview to see suggested entries"
			exit 1
		fi
		;;
	"changelog-preview")
		print_info "Generating changelog preview from commits..."
		echo ""
		generate_changelog_preview
		;;
	"auto-mark-tasks")
		print_info "Auto-marking tasks complete from commit messages..."
		auto_mark_tasks_complete
		;;
	"list-task-ids")
		print_info "Task IDs found in commits since last release:"
		extract_task_ids_from_commits
		;;
	*)
		_main_usage
		;;
	esac
	return 0
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	main "$@"
fi
